
version: '3.8'

services:
  
  db:
    image: postgres:14-alpine  
    container_name: svits-postgres-db
    environment:
      POSTGRES_DB: svits_local_db       
      POSTGRES_USER: localuser          
      POSTGRES_PASSWORD: localpassword  
    ports:
      
      
      - "5432:5432"
    volumes:
      
      
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data:


docker-compose.yml