# =================== Producción desde Render ===================
spring.datasource.url=jdbc:postgresql://192.168.0.13:5432/svitsdb
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# correo desde variables de entorno
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${SPRING_MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.debug=false

# Auth0 desde variables de entorno
spring.security.oauth2.client.registration.auth0.client-id=${AUTH0_CLIENT_ID}
spring.security.oauth2.client.registration.auth0.client-secret=${AUTH0_CLIENT_SECRET}
spring.security.oauth2.client.registration.auth0.scope=openid,profile,email
spring.security.oauth2.client.provider.auth0.issuer-uri=https://dev-4u02s5zko50e5w47.us.auth0.com/

management.endpoints.web.exposure.include=*

# === Perfil solo para mi maquina local  ===
# perfil adicional si está disponible para hacer pruebas.
spring.profiles.active=dev