# =================== DATOS PRINCIPALES ===================
spring.datasource.url=jdbc:postgresql://dpg-d024smruibrs73ahi1s0-a:5432/svitsdb
spring.datasource.username=svits_user
spring.datasource.password=uEnxnby3qOCoE1eyU9L6T7uB1kpe7jjZ
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# --- LÍNEA AÑADIDA ---
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# =================== EMAIL ===================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=alertas.svits@gmail.com
spring.mail.password=myrq mwsq yben gfrw
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.debug=true # Puedes quitarla si ya no necesitas logs detallados de correo

spring.datasource.initialization-mode=always

# =================== ACTUATOR ===================
management.endpoints.web.exposure.include=*

# =================== CONEXIONES ADICIONALES PARA HEALTH CHECK ===================
# Estas probablemente no funcionarán en Render y podrían eliminarse o comentarse
# mysql.url=jdbc:mysql://host.docker.internal:3306/
# mysql.username=root
# mysql.password=
#
# oracle.url=jdbc:oracle:thin:@host.docker.internal:1521:xe
# oracle.username=svits
# oracle.password=svits123

# error reparado
