


spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/svits_local_db_placeholder}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:local_db_user_placeholder}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:local_db_password_placeholder}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${SPRING_MAIL_USERNAME:your_generic_username_placeholder@example.com}
spring.mail.password=${SPRING_MAIL_PASSWORD:your_generic_password_placeholder}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.debug=false

spring.datasource.initialization-mode=always

management.endpoints.web.exposure.include=*

spring.security.oauth2.client.registration.auth0.client-id=${AUTH0_CLIENT_ID}
spring.security.oauth2.client.registration.auth0.client-secret=${AUTH0_CLIENT_SECRET}
spring.security.oauth2.client.registration.auth0.scope=openid,profile,email
spring.security.oauth2.client.provider.auth0.issuer-uri=https://${AUTH0_DOMAIN}/

spring.security.oauth2.resourceserver.jwt.issuer-uri=https://${AUTH0_DOMAIN}/
spring.security.oauth2.resourceserver.jwt.audience=${AUTH0_AUDIENCE}










# Para uso local solamente

# mysql.url=jdbc:mysql://localhost:3306/local_mysql
# mysql.username=localmysqluser
# mysql.password=localmysqlpass
#
# oracle.url=jdbc:oracle:thin:@localhost:1521:XE
# oracle.username=localoracleuser
# oracle.password=localoraclepass